{% set version = "2.0.2" %}

package:
  name: nuflux
  version: {{ version }}

source:
  url: https://github.com/icecube/nuflux/archive/refs/tags/v{{ version }}.tar.gz
  sha256: 3c9d319a1c24c7327c5e30856d9b66e97c829f6dc07c86f9ff5178e6f4505208

build:
  number: 2
  skip: true  # [win]

requirements:
  build:
    - python
    - cross-python_{{ target_platform }}     # [build_platform != target_platform]
    - numpy
    - meson
    - cmake
    - ninja
    - pkg-config
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
  host:
    - python
    - numpy >=1.7
    - cfitsio
    - photospline
    - boost
  run:
    - python
    - numpy
    - cfitsio
    - photospline
    - boost

test:
  source_files:
    - tests
  commands:
    - cd tests && $PYTHON test_fluxes.py

about:
  home: https://github.com/icecube/nuflux
  license: LGPL-3.0-only
  license_family: GPL3
  license_file: LICENSE
  summary: Library for calculating atmospheric neutrino fluxes
  dev_url: https://github.com/icecube/nuflux

extra:
  recipe-maintainers:
    - jvansanten
