{% set version = "2.0.5" %}

package:
  name: nuflux
  version: {{ version }}

source:
  url: https://github.com/icecube/nuflux/archive/refs/tags/v{{ version }}.tar.gz
  sha256: 65cb0c284cc46e1006f1eb1fba296b84e30a148d4386887de152961ba711d6b8

build:
  number: 1
  skip: true  # [win or python_impl == "pypy"]

requirements:
  build:
    - python
    - cross-python_{{ target_platform }}     # [build_platform != target_platform]
    - numpy
    - meson
    - cmake
    - ninja
    - pkg-config
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
  host:
    - python
    - numpy >=1.7
    - cfitsio
    - photospline
    - libboost-python-devel
  run:
    - python
    - numpy
    - cfitsio
    - photospline
    - libboost-python-devel

test:
  source_files:
    - tests
  requires:
    - pytest
    - pytest-subtests
  commands:
    - cd tests && $PYTHON test_fluxes.py

about:
  home: https://github.com/icecube/nuflux
  license: LGPL-3.0-only
  license_family: GPL3
  license_file: LICENSE
  summary: Library for calculating atmospheric neutrino fluxes
  dev_url: https://github.com/icecube/nuflux

extra:
  recipe-maintainers:
    - jvansanten
